---
- name: Configure Device
  hosts: 66.129.234.215
  connection: local
  gather_facts: no

  tasks:
    - name: Configure op script
      junos_config:
        check_commit: no
        update: merge
        lines:
          - set system host-name {{ hostname }}
          - set system ntp server 10.10.10.10
          - set system ntp server 11.11.11.11
          - set system ntp server {{ ntp_server }}
        comment: update of ntp config

